### PR TITLE
Fix issue #20

### PR DESCRIPTION
**Pull request by benvanmierloo**
Refresh tokens aren't automatically extended anymore. 
Every time credentials are provided a new refresh_token is generated
If a refresh is done and if the refresh_token is still valid, this refresh_token will be kept, no new one generated

### CODE REVIEW

**Comment by markitosgv** [comment]
Please fix and add new tests, fix style CI

**Comment by benvanmierloo** [comment]
could you help me with that? Or you could just copy the few lines of changed code into your project, I dont mind.

**Comment by benvanmierloo** [comment]
StyleCI passes now. Also I updated the testcases and locally they all succeed, but the travis-ci build for PHP 5.3 fails:
> "PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 32 bytes) in phar:///home/travis/.phpenv/versions/5.3.29/bin/composer/src/Composer/DependencyResolver/RuleWatchGraph.php on line 52". 

I don't know how to fix this... Any ideas?

**Comment by benvanmierloo** [comment]
(temporarily) disabled PHP 5.3 in .travis.yml

**Comment by markitosgv** [comment]
@benvanmierloo can you squash your commits please? Tomorrow i try to Merge
your PR. Thanks!

**Comment by benvanmierloo** [comment]
Done

**Pull request closed without merging**
