### PR TITLE
Use a UserChecker

### LINKED ISSUE #52: Security issue: Loadable users are always authenticated
The current implementation to refresh JWT tokens is not safe. When a user presents a refresh token, the only check that occurs is whether the user provider can load the user. If a user is loadable, it is granted a new access token.

But the authenticator should also check if the loaded user is still allowed to access the application. For example, users that implement the AdvancedUserInterface should be checked whether their account is enabled, is not locked and is not expired. Other means of authentication may have other requirements (e.g. for OAuth accounts, check whether the correct permissions are still present).

Currently, this bundle will happily give out new access tokens to users who have been disabled, expired, etc.

I think there should be some way to hook into the authenticator to provide this logic. Or perhaps the authenticator in this bundle should delegate authentication to some other authentication provider.

Currently I am using a compiler pass to overwrite the authenticator provided in this bundle with my own. That's a bit of a hackish solution.

### PR DESCRIPTION
**Pull request by sandermarechal**
Use a UserChecker during authentication. This fixes #52

### CODE REVIEW

**Comment by sandermarechal** [comment]
Perhaps the documentation should even go as far as recommending (or requiring?) to set a user provider? Not doing so is a security issue. The default user checker checks for inactive or locked accounts, but users generated by this bundles user_provider generally pass all those checks, even when the should not.

**Comment by juliusstoerrle** [comment]
What's the plan for this merge request? We need this feature in order to use this Bundle and would appreciate if those changes would be merged.

**Comment by lashae** [comment]
Is there any progress or ETA about merging this PR?

**Comment by xthiago** [comment]
I'm guess the project was abandoned. The author does not reply any pull-request. I'm considering creating a fork project.

**Comment by markitosgv** [comment]
@xthiago Im searching for some collaborators to help me with this repository, do you want to participate?

**Comment by markitosgv** [comment]
@sandermarechal colud you please up to date this PR and resolve conflicts for merging? thanks

**Comment by sandermarechal** [comment]
I have rebased on master and resolved all the conflicts. Only, I could not run the tests locally because I do not have the mongodb extension installed and composer refuses to install. Perhaps the mongodb extension should be optional for testing, just skipping the tests?

**Pull request merged**
