### PR TITLE
Updating to symfony 4 [No BC Break]

### PR DESCRIPTION
**Pull request by aequasi**

### CODE REVIEW

**Comment by aequasi** [comment]
The ONLY thing im not sure about, is if the auto-wiring will throw errors in 2.x?

Tests are failing due to pre-existing issues, wont fix.

**Comment by markitosgv** [comment]
Could you test with Symfony 2.x branch to assurance NO BC breaking?

**Comment by aequasi** [comment]
It did NOT work in 2.x. I manually wired, and fixed that issue

**Comment by aequasi** [comment]
Any updates @markitosgv

**Comment by aequasi** [comment]
The work is already finished @blaugueux

**Comment by aequasi** [comment]
Looks like another PR was already merged for this? Seems like it was missing stuff to be fully SF4 compatible though.

**Comment by markitosgv** [comment]
Already sf4 compatible

**Pull request closed without merging**
